# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Adi Reddy Mora
tagline:             '@adireddy - arm.rocks'
description:         '"A problem is a chance for you to do your best." -- Duke Ellington'
url:                 http://www.arm.rocks
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Adi Reddy Mora
  url:               http://www.arm.rocks
  email:             adiinteractive@gmail.com

# Custom vars
version:             1.0.0
