# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Adi Reddy Mora
tagline:             ''
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Adi Reddy Mora
  url:               http://www.arm.rocks
  email:             adiinteractive@gmail.com

# Custom vars
version:             1.0.0
